name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Build
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios12.1-simulator"
        working-directory: ./
